apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
        - job_name: "pure-k8s-prometheus-app"
          static_configs:
            - targets: ["pure-k8s-prometheus-app:5000"]
